export const ALL_LAYERS = [
    { id: 'LP_PA_CBND_BUBUN', label: '지적도', category: '기본' },

    { id: 'LT_C_UQ111', label: '도시지역', category: '용도지역' },
    { id: 'LT_C_UQ112', label: '관리지역', category: '용도지역' },
    { id: 'LT_C_UQ113', label: '농림지역', category: '용도지역' },
    { id: 'LT_C_UQ114', label: '자연환경보전지역', category: '용도지역' },

    { id: 'LT_C_UQ129', label: '개발진흥지구', category: '용도지구' },
    { id: 'LT_C_UQ121', label: '경관지구', category: '용도지구' },
    { id: 'LT_C_UQ123', label: '고도지구', category: '용도지구' },
    { id: 'LT_C_UQ122', label: '미관지구', category: '용도지구' },
    { id: 'LT_C_UQ125', label: '방재지구', category: '용도지구' },
    { id: 'LT_C_UQ124', label: '방화지구', category: '용도지구' },
    { id: 'LT_C_UQ126', label: '보존지구', category: '용도지구' },
    { id: 'LT_C_UQ127', label: '시설보호지구', category: '용도지구' },
    { id: 'LT_C_UQ128', label: '취락지구', category: '용도지구' },
    { id: 'LT_C_UQ130', label: '특정용도제한지구', category: '용도지구' },

    { id: 'LT_C_UD801', label: '개발제한구역', category: '용도구역' },
    { id: 'LT_C_UQ141', label: '국토계획구역', category: '용도구역' },
    { id: 'LT_C_UQ162', label: '도시자연공원구역', category: '용도구역' },
    { id: 'LT_C_UM000', label: '가축사육제한구역', category: '용도구역' },
    { id: 'LT_C_UO601', label: '관광지', category: '용도구역' },
    { id: 'LT_C_UD610', label: '국민임대주택', category: '용도구역' },
    { id: 'LT_C_UP401', label: '급경사재해예방지역', category: '용도구역' },
    { id: 'LT_C_UM301', label: '대기환경규제지역', category: '용도구역' },
    { id: 'LT_C_UF901', label: '백두대간보호지역', category: '용도구역' },
    { id: 'LT_C_UH701', label: '벤처기업육성지역', category: '용도구역' },
    { id: 'LT_C_UD620', label: '보금자리주택', category: '용도구역' },
    { id: 'LT_C_UF151', label: '산림보호구역', category: '용도구역' },
    { id: 'LT_C_UM901', label: '습지보호지역', category: '용도구역' },
    { id: 'LT_C_UB901', label: '시장정비구역', category: '용도구역' },
    { id: 'LT_C_UM221', label: '야생동식물보호', category: '용도구역' },
    { id: 'LT_C_UJ401', label: '온천지구', category: '용도구역' },
    { id: 'LT_C_UH501', label: '유통단지', category: '용도구역' },
    { id: 'LT_C_UH402', label: '자유무역지역', category: '용도구역' },
    { id: 'LT_C_UD601', label: '주거환경개선지구도', category: '용도구역' },
    { id: 'LT_C_UO101', label: '학교환경위생정화구역', category: '용도구역' },

    { id: 'LT_C_LHZONE', label: '사업지구경계도', category: '도시계획' },
    { id: 'LT_C_LHBLPN', label: '토지이용계획도(LH)', category: '도시계획' },
    { id: 'LT_C_UPISUQ153', label: '도시계획(공간시설)', category: '도시계획' },
    { id: 'LT_C_UPISUQ155', label: '도시계획(공공문화)', category: '도시계획' },
    { id: 'LT_C_UPISUQ152', label: '도시계획(교통시설)', category: '도시계획' },
    { id: 'LT_C_UPISUQ159', label: '도시계획(기타)', category: '도시계획' },
    { id: 'LT_C_UPISUQ151', label: '도시계획(도로)', category: '도시계획' },
    { id: 'LT_C_UPISUQ156', label: '도시계획(방재시설)', category: '도시계획' },
    { id: 'LT_C_UPISUQ157', label: '도시계획(보건위생)', category: '도시계획' },
    { id: 'LT_C_UPISUQ154', label: '도시계획(유통공급)', category: '도시계획' },
    { id: 'LT_C_UPISUQ158', label: '도시계획(환경기초)', category: '도시계획' },
    { id: 'LT_C_UPISUQ161', label: '지구단위계획', category: '도시계획' },
    { id: 'LT_C_UPISUQ171', label: '개발행위허가제한', category: '도시계획' },
    { id: 'LT_C_UPISUQ174', label: '개발행위허가필지', category: '도시계획' },
    { id: 'LT_C_UPISUQ173', label: '기반시설부담구역', category: '도시계획' },
    { id: 'LT_C_UPISUQ175', label: '토지거래허가구역', category: '도시계획' },

    { id: 'LT_C_KFDRSSIGUGRADE', label: '산불위험예측지도', category: '환경/산림' },
    { id: 'LT_C_AGRIXUE101', label: '농업진흥지역도', category: '환경/산림' },
    { id: 'LT_C_AGRIXUE102', label: '영농여건불리농지', category: '환경/산림' },
    { id: 'LT_C_FLISFK300', label: '산지(보안림)', category: '환경/산림' },
    { id: 'LT_C_FLISFK100', label: '산지(자연휴양림)', category: '환경/산림' },
    { id: 'LT_C_FLISFK200', label: '산지(채종림)', category: '환경/산림' },
    { id: 'LT_C_UF602', label: '임업및산촌진흥권역', category: '환경/산림' },
    { id: 'LT_C_FSDIFRSTS', label: '산림입지도', category: '환경/산림' },

    { id: 'LT_C_UP201', label: '재해위험지구', category: '재해/안전' },
    { id: 'LT_P_EDRSE002', label: '지진대피소', category: '재해/안전' },
    { id: 'LT_P_ETQSHELTER', label: '지진해일대피소', category: '재해/안전' },
    { id: 'LT_C_USFSFFB', label: '소방서관할구역', category: '재해/안전' },
    { id: 'LT_C_CDFRS100FRQ', label: '해안침수(100년)', category: '재해/안전' },
    { id: 'LT_C_CDFRSMAXFRQ', label: '해안침수(최대범람)', category: '재해/안전' },

    { id: 'LT_C_WGISPLTALK', label: '개발유도연안', category: '수자원/해양' },
    { id: 'LT_C_WGISPLROW', label: '개발조정연안', category: '수자원/해양' },
    { id: 'LT_C_WGISPLUSE', label: '이용연안', category: '수자원/해양' },
    { id: 'LT_C_WGISPLABS', label: '절대보전연안', category: '수자원/해양' },
    { id: 'LT_C_WGISPLJUN', label: '준보전연안', category: '수자원/해양' },
    { id: 'LT_C_WKMSBSN', label: '표준권역(수자원)', category: '수자원/해양' },
    { id: 'LT_C_WKMSTRM', label: '하천망', category: '수자원/해양' },
    { id: 'LT_C_UM710', label: '상수원보호', category: '수자원/해양' },
    { id: 'LT_C_WGISARFISHER', label: '수산자원보호구역', category: '수자원/해양' },
    { id: 'LT_C_WGISARWET', label: '습지보호구역', category: '수자원/해양' },
    { id: 'LT_L_TOISDEPCNTAH', label: '해안선', category: '수자원/해양' },

    { id: 'LT_C_ADSIDO', label: '광역시도', category: '행정/기타' },
    { id: 'LT_C_ADSIGG', label: '시군구', category: '행정/기타' },
    { id: 'LT_C_ADEMD', label: '읍면동', category: '행정/기타' },
    { id: 'LT_C_RI', label: '리', category: '행정/기타' },
    { id: 'LT_L_SPRD', label: '도로명주소도로', category: '행정/기타' },
    { id: 'LT_C_SPBD', label: '도로명주소건물', category: '행정/기타' },
    { id: 'LT_P_NSNMSSITENM', label: '국가지명', category: '행정/기타' }
];

export const QUICK_LAYER_IDS = [
    'LP_PA_CBND_BUBUN',
    'LT_C_UQ111',
    'LT_C_UQ112',
    'LT_C_UQ113',
    'LT_C_UQ114',
    'LT_C_UD801'
];

export const BASIC_LAYERS = ['LT_C_UQ111', 'LT_C_UQ112', 'LT_C_UQ113', 'LT_C_UQ114'];
